#!/bin/bash
#SBATCH --job-name=exmamenblast
#SBATCH --output=examenblast.txt
#SBATCH --partition=nu
#SBATCH --ntasks=1
#SBATCH --time=70:00:00
#SBATCH --mail-user=curso-632@kabre.centa.ac.cr

module load blast+/2.11.0

makeblastdb -in a.chroococcum.fna -input_type fasta -dbtype nucl -parse_seqids

blastn -query d.acidovorans.fna -task blastn -db a.chroococcum.fna -out examenblast.txt -evalue 1e-5 -outfmt '6' -num_threads 48
